name: Deploy

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: compile
        run: make
      - uses: docker://pandoc/core:2.9
        with:
          args: "--help" # gets appended to pandoc command
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
